server:
  port: 8082

spring:
  application:
    name: activity-service
  mongodb:
    uri: ${MONGODB_ACTIVITY_URI}
    database: fitnessactivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking