server:
  port: 8083

spring:
  application:
    name: ai-service
  mongodb:
    uri: ${MONGODB_RECOMMENDATION_URI}
    database: fitnessrecommendation
  rabbitmq:
    addresses: ${RABBITMQ_URL}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

ai:
  api:
    url: ${AI_API_URL}
    key: ${AI_API_KEY}